(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3DAEF2").s().p("Aw/XYQhyhVhohpQoeodAAr9QAAr8IeoeQIdodL8AAQL+AAIdIdIAiAjQH7ITAALkQAAL9odIdQodIer+AAQpoAAnXlgg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-184.7,-184.7,369.6,369.6);


(lib.Tween19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.text = new cjs.Text("SUBURB", "20px 'Apercu'", "#263238");
	this.text.textAlign = "right";
	this.text.lineHeight = 27;
	this.text.lineWidth = 114;
	this.text.parent = this;
	this.text.setTransform(186.8,-52.9,5.522,5.522);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-452,-64,649.9,150.5);


(lib.Tween18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("A/YPbIfn++IfKfHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-200.8,-99.6,401.8,199.2);


(lib.Tween17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B5FFFF").s().p("A0pOKIAA8UMApTAAAIAAcUg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.2,-90.6,264.4,181.3);


(lib.Tween15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("A9aujMA61AAAI9kdHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-188.2,-93.1,376.6,186.3);


(lib.Tween13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B5FFFF").s().p("Au3u/IWnAAIHIAAInIHMI2nWzg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-95.2,-96,190.4,192);


(lib.Tween9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.8,-134.1,257.6,268.3);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B5FFFF").s().p("A8WOMIcY8XIcVcXg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181.5,-90.8,363,181.6);


(lib.triangles = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#263238").s().p("AjONHIA+h6IA+B7gAoENHIA+h6IA+B7gAs5NHIA+h6IA+B7gAxvNHIA+h6IA+B7gAP+NDIA+h6IA+B7gALJNDIA+h6IA+B7gAGTNDIA+h6IA+B7gABeNDIA+h6IA+B7gASVIQIA+h7IA+B8gAlrIQIA+h7IA+B8gAqhIQIA+h7IA+B8gAvWIQIA+h7IA+B8gA0MIQIA+h7IA+B8gANiILIA+h5IA+B6gAIrILIA+h5IA+B6gAD2ILIA/h5IA+B6gAg+ILIA9h5IA9B6gAjSDbIA+h6IA+B7gAoIDbIA+h6IA+B7gAs9DbIA+h6IA+B7gAxzDbIA+h6IA+B7gAP7DXIA+h6IA+B7gALEDXIA+h6IA+B7gAGPDXIA/h6IA+B7gABaDXIA9h6IA+B7gASThbIA+h7IA+B8gANdhbIACgFIgCAAIA+h5IA+B6IgCAAIACAFgAlvhbIA+h7IA+B8gAqlhbIA+h7IA+B8gAvahbIA+h7IA+B8gA0QhbIA+h7IA+B8gAIohgIA+h5IA+B6gADzhgIA9h5IA+B6gAhDhgIA+h5IA+B6gAjSmOIA+h6IA+B7gAoImOIA+h6IA+B7gAs9mOIA+h6IA+B7gAxzmOIA+h6IA+B7gAP7mSIA+h6IA+B7gALEmSIA+h6IABABIAAgBIA+B7gAGPmSIA/h6IA+B7gABamSIA9h6IA+B7gAlvrGIA+h6IA+B7gAqlrGIA+h6IA+B7gAvarGIA+h6IA+B7gA0QrGIA+h6IA+B7gADzrJIAAAAIAAAAIA9h7IA+B8IAAAAIAAAAgAhDrJIA+h7IA+B8gASLrNIA+h6IA+B7gANVrNIA+h6IA+B7gAIfrNIA+h6IA+B7g");
	this.shape.setTransform(129.7,83.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.triangles, new cjs.Rectangle(0,-0.3,259.4,168), null);


(lib.stripepattern = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#263238").s().p("AYbM0I5p5mIAcgBIZpZngAViM0I5b5ZIAagCIZdZbgASsM0I5A4/IAXgFIZFZEgAP1M0I4b4ZIAWgHIYhYggAM/M0I3s3qIAVgIIXzXygAKGM0I2z2xIATgJIW8W6gAHRM0I1z1xIASgLIV9V8gAEZM0I0r0pIARgLIU2U0gABjM0IzdzbIAQgNITpTogAhVM0IyIyGIAPgNISVSTgAkLM0IwtwsIAOgOIQ8Q6gAnBM0IvOvLIANgQIPdPbgAp2M0ItptmIAMgRIN5N3gAsvM0Ir7r6IALgRIMMMLgAvlM0IqHqGIAKgTIKZKZgAydM0IoLoKIAJgUIIfIegA1SM0ImImHIAIgVIGcGcgA4LM0Ij4j3IAGgXIEOEOgA7BM0IhghgIAEgYIB4B4gAbIMsI5g5dIAeACIZeZbgAchLNI3u3qIAiAGIXHXEIABAHIAFAagAIfrnIAqAMISWSVIANAogANUpqIA/AjIK3K2IAjA/g");
	this.shape.setTransform(182.6,82);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.stripepattern, new cjs.Rectangle(0,0,365.2,164), null);


(lib.pattern = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#263238").s().p("AyfVcIABAAIAAAAgASIUMIhshrIhrBrIhaAAIhehfIhgBfIgtAAICNiNICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIhHBHgAIrUMIhghgIhgBgIguAAICOiNICOCNgAD5UMIhehdIhdBdIguAAICMiLICLCLgAg3UMIhRhRIhRBRIgtAAIB/h/IB+B/gAljUMIhShSIhSBSIguAAICAh/ICAB/gAqTUMIhRhSIhSBSIguAAICAiAICACAgAvDUMIhGhGIhFBGIgtAAIBzhzIBzBzgAzwUMIg3g3IAAguIBlBlgAyhTSIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhRNIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhPFIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhMgIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhKYIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhITIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhGLIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhEEIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhB8IAAAAIiGiEIAAguICGCFIAAAAIADACICWiVICMCKICYiXICWCVIAAABIABABICYiWICVCTIAAAAIACACICXiVICLCLICYiXICWCVIAAgCIABABICYiWICVCTIABAAIACACICWiVICLCLICZiXICWCVIAAABIABABIB0hzIAAAuIh0ByIgBgBIAAgBIgBgBIAAAAIiWiTIiYCWIgCgCIAAAAIiJiIIiWCVIgCgCIgBAAIiViUIiYCXIgBgBIAAABIgBgBIgBAAIiViTIiXCWIgDgCIAAAAIiJiIIiWCVIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCVgAyhgIIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhiQIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhklIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhmtIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhoyIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhq6IAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhtBIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhvJIAAAAIiGiFIAAguICGCGIAAAAIADACICWiWICMCLICYiYICWCWIAAABIABABICYiXICVCUIAAAAIACACICXiWICLCMICYiYICWCWIAAgCIABABICYiXICVCUIABAAIACACICWiWICLCMICZiYICWCWIAAABIABABIB0h0IAAAuIh0BzIgBgBIAAgBIgBgBIAAAAIiWiUIiYCXIgCgCIAAAAIiJiJIiWCWIgCgCIgBAAIiViVIiYCYIgBgBIAAABIgBgBIgBAAIiViUIiXCXIgDgCIAAAAIiJiJIiWCWIgCgCIAAAAIiViVIiYCYIgBgBIAAgBIgBgBIgBAAIiUiVIiYCYIgCgCIgBAAIiKiKIiVCWgAyhxOIAAAAIiGiGIAAgtICGCFIAAAAIADACICWiWICMCMICYiYICWCWIAAABIABABICYiYICVCVIAAAAIACACICXiWICLCLICYiYICWCWIAAgBIABABICYiYICVCVIABAAIACACICWiWICLCLICZiYICWCWIAAABIABABIB0hzIAAAtIh0B0IgBgBIAAgBIgBgBIAAAAIiWiVIiYCYIgCgCIAAAAIiJiKIiWCWIgCgCIgBAAIiViUIiYCXIgBgBIAAACIgBgBIgBAAIiViVIiXCYIgDgCIAAAAIiJiKIiWCWIgCgCIAAAAIiViUIiYCXIgBgBIAAgBIgBgBIgBAAIiUiUIiYCXIgCgCIgBAAIiKiJIiVCWgAyhzWIAAAAIiFiFIAtAAIBYBXIAAAAIADACIBZhZIAuAAIiHCHgApOzgIAAgBIgBgBIgBAAIh5h5IAuAAIBNBNIAAABIABABIBPhPIAuAAIh9B8gAt+zhIgBAAIh7h6IAuAAIBQBPIBPhPIAuAAIh9B8gAkgziIAAAAIh6h5IAuAAIBMBMIAAAAIACACIBPhOIAtAAIh8B7gAABzsIAAAAIhuhvIAuAAIBDBDIBDhDIAuAAIhxBxgAExztIgBAAIhuhuIAvAAIBBBBIAAgBIABABIBBhBIAuAAIhvBuIgBgBIAAACgAJhzwIgBAAIhshrIAuAAIA+A+IABAAIACACIBAhAIAtAAIhtBtgASzz5IAAgBIgBgBIAAAAIhhhgIAuAAIA0AzIAAABIABABIA2g1IAuAAIhkBjgAOCz6IAAAAIhhhhIAuAAIA1A1IA2g1IAuAAIhkBjg");
	this.shape.setTransform(132,147.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F2F2F2").s().p("A0rU0MAAAgpnMApXAAAMAAAApng");
	this.shape_1.setTransform(132,143.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.pattern, new cjs.Rectangle(-0.3,9.9,264.8,274.5), null);


(lib.linepattern = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#263238").s().p("AhIcFIdK9XIA/A/I9KdXgAjQZ4IdG9TIA/A/I9GdTgAlVX0IdG9TIA/A/I9GdTgAnfVqIdF9TIBAA/I9GdTgApoTfIdD9RIA/A/I9DdRgAryRUIdD9PIA+A+I9CdQgAt9PQIdF9SIBAA+I9GdTgAwHNGIdE9SIA/A/I9EdSgAyQK7IdD9RIA/A/I9DdRgA0aIwIdC9PIBAA+I9DdQgA2iGqIdC9QIA/A/I9CdQgA4sEfIdB9PIA/A/I9BdPgA62CUIdB9NIA/A/I9BdNgA9AAKIdA9NIA/A/I9AdNg");
	this.shape.setTransform(185.7,186);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.linepattern, new cjs.Rectangle(0,0,371.3,372), null);


(lib.dotpattern = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#263238").s().p("AgDUKIgEgEIgBgEIABgFQACgFAFAAIABAAQAGAAADAGQACAHgFAEQgDACgEAAIgDgBgAi6UKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAlxUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAooUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAreUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAuVUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAxMUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgA0DUKIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAT8UJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgARFUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAOOUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgALXUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAIhUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAFqUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgACzUJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgABYRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAheRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAkVRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAnMRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAqCRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAs5RVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAvwRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAynRVIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAShRUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAPqRUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAMzRUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAJ9RUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAHGRUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAEPRUIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAgDOcIgEgEIgBgEIABgGQACgEAFAAIABgBQAGAAADAHQACAGgFAEQgDACgEAAIgDAAgAi6OcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAlxOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAooOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAreOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAuVOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAxMOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgA0DOcIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAT8ObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgARFObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAOOObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgALXObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAIhObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAFqObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgACzObIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgABYLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAheLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAkVLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAnMLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAqCLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAs5LnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAvwLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAynLnIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAShLmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAPqLmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAMzLmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAJ9LmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAHGLmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAEPLmIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAgDIvIgEgEIgBgEIABgGQACgEAFAAIABgBQAGAAADAHQACAGgFAEQgDACgEAAIgDAAgAi6IvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAlxIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAooIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAreIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAuVIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAxMIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgA0DIvIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAT8IuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgARFIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAOOIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgALXIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAIhIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAFqIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgACzIuIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgABYF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAheF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAkVF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAnMF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAqCF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAs5F6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAvwF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAynF6IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAShF5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAPqF5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAMzF5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAJ9F5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAHGF5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAEPF5IgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAgDDAIgEgEIgBgEIABgFQACgFAFAAIABAAQAGAAADAGQACAHgFAEQgDACgEAAIgDgBgAi6DAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAlxDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAooDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAreDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAuVDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAxMDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgA0DDAIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAT8C/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgARFC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAOOC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgALXC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAIhC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAFqC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgACzC/IgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgABYALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAheALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAkVALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAnMALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAqCALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAs5ALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAvwALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAynALIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAShAKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAPqAKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAMzAKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAJ9AKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAHGAKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAEPAKIgEgEIgBgEIABgEQADgFAEAAIACAAQAHAAACAGQACAGgFAEQgDACgDAAIgFgBgAgDisIgEgEIgBgEIABgGQACgEAFAAIABgBQAGAAADAHQACAGgFAEQgDACgEAAIgDAAgAi6isIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAlxisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAooisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAreisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAuVisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAxMisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgA0DisIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAT8itIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgARFitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAOOitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgALXitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAIhitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAFqitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgACzitIgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgABYlhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAhelhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAkVlhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAnMlhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAqClhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAs5lhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAvwlhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAynlhIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAShliIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAPqliIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAMzliIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAJ9liIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAHGliIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAEPliIgEgEIgBgEIABgGQADgEAEAAIACgBQAHAAACAHQACAGgFAEQgDACgDAAIgFAAgAgDobIgEgEIgBgEIABgFQACgFAFAAIABAAQAGAAADAGQACAHgFAEQgDACgEAAIgDgBgAi6obIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAlxobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAooobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAreobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAuVobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAxMobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgA0DobIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAT8ocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgARFocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAOOocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgALXocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAIhocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAFqocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgACzocIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgABYrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAherQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAkVrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAnMrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAqCrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAs5rQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAvwrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAynrQIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAShrRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAPqrRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAMzrRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAJ9rRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAHGrRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAEPrRIgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAgDuIIgEgEIgBgEIABgFQACgFAFAAIABAAQAGAAADAGQACAHgFAEQgDACgEAAIgDgBgAi6uIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAlxuIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAoouIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAreuIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAuVuIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAxMuIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgA0DuIIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAT8uJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgARFuJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAOOuJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgALXuJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAIhuJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgAFquJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgACzuJIgEgEIgBgEIABgFQACgFAFAAIACAAQAGAAADAGQACAHgFAEQgDACgEAAIgEgBgABYw9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAhew9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAkVw9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAnMw9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAqCw9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAs5w9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAvww9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAynw9IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAShw+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAPqw+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAMzw+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAJ9w+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAHGw+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAEPw+IgEgEIgBgEIABgFQADgFAEAAIACAAQAHAAACAGQACAHgFAEQgDACgDAAIgFgBgAxQz3QgDgDAAgFQAAgEADgDQADgEAEAAQAEAAACACQADACACAEIAAAGIgDAFQgDADgFAAQgEAAgDgDgA0Hz3QgDgDAAgFQAAgEADgDQADgEAFAAQAEAAADAEQAEADAAAEQAAAFgEADQgDADgEAAQgFAAgDgDgAgDz2IgEgEIgBgEIABgGQACgEAFAAIABgBQAGAAADAHQACAGgFAEQgDACgEAAIgDAAgAi6z2IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAlxz2IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAooz2IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgArez2IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAuVz2IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAT8z3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgARFz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAOOz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgALXz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAIhz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgAFqz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAgACzz3IgEgEIgBgEIABgGQACgEAFAAIACgBQAGAAADAHQACAGgFAEQgDACgEAAIgEAAg");
	this.shape.setTransform(129.1,129.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.dotpattern, new cjs.Rectangle(0,0,258.1,258.2), null);


(lib.ClipGroup_53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjEDFIAAmJIGJAAIAAGJg");
	mask.setTransform(19.7,19.7);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("AjEDFIAAmJIGJAAIAAGJgAiqCrIFVAAIAAlWIlVAAg");
	this.shape.setTransform(19.7,19.7);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_53, new cjs.Rectangle(0,0,39.4,39.4), null);


(lib.ClipGroup_52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjEDEIAAmHIGJAAIAAGHg");
	mask.setTransform(19.7,19.6);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B5FFFF").s().p("AiKCLQg6g6AAhRQAAhQA6g6QA6g5BQAAQBSAAA5A5QA6A6AABQQAABRg6A6Qg5A5hSAAQhQAAg6g5gAh4h4QgxAyAABGQAABHAxAyQAyAyBGAAQBHAAAygyQAygyAAhHQAAhGgygyQgygyhHAAQhGAAgyAyg");
	this.shape.setTransform(19.7,19.6);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_52, new cjs.Rectangle(0,0,39.3,39.3), null);


(lib.ClipGroup_19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AlaCuIAAlbIK0AAIAAFbg");
	mask.setTransform(34.7,17.4);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("Aj0BIQhmhlAAiQIK0AAQABCQhmBlQhlBliQABQiPgBhlhlg");
	this.shape.setTransform(34.7,17.4);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_19, new cjs.Rectangle(0,0,69.3,34.7), null);


(lib.ClipGroup_14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80D8FF").s().p("AhHD1QhlhlAAiQQAAiOBlhmQBlhmCPAAIAAK1QiPAAhlhmg");
	this.shape.setTransform(17.3,34.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_14, new cjs.Rectangle(0,0,34.7,69.4), null);


(lib.ClipGroup_9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AisFbIAAq1IFZAAIAAK1g");
	mask.setTransform(17.3,34.7);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B5FFFF").s().p("AislaQCPAABlBmQBlBmAACOQAACQhlBlQhlBmiPAAg");
	this.shape.setTransform(17.3,34.7);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_9, new cjs.Rectangle(0,0,34.7,69.4), null);


(lib.Tween7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.triangles();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0.2,1,1,0,0,0,129.7,83.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129.6,-84,259.4,168);


(lib.Group_1_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ClipGroup_53();
	this.instance.parent = this;
	this.instance.setTransform(19.7,19.7,1,1,0,0,0,19.7,19.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_1_4, new cjs.Rectangle(0,0,39.4,39.4), null);


(lib.ClipGroup_13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.ClipGroup_14();
	this.instance.parent = this;
	this.instance.setTransform(17.3,34.6,1,1,0,0,0,17.3,34.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_13, new cjs.Rectangle(0,0,34.7,69.4), null);


(lib.ClipGroup_8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AisFbIAAq1IFZAAIAAK1g");
	mask.setTransform(17.3,34.7);

	// Layer 3
	this.instance = new lib.ClipGroup_9();
	this.instance.parent = this;
	this.instance.setTransform(17.3,34.6,1,1,0,0,0,17.3,34.6);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_8, new cjs.Rectangle(0,0,34.7,69.4), null);


(lib.Group_3_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ClipGroup_8();
	this.instance.parent = this;
	this.instance.setTransform(17.3,34.6,1,1,0,0,0,17.3,34.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_3_0, new cjs.Rectangle(0,0,34.7,69.4), null);


(lib.Group_2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ClipGroup_13();
	this.instance.parent = this;
	this.instance.setTransform(17.3,34.6,1,1,0,0,0,17.3,34.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group_2_1, new cjs.Rectangle(0,0,34.7,69.4), null);


// stage content:
(lib.BauhausSuburb1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Suburb
	this.instance = new lib.Tween19("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-200.4,436.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(53).to({_off:false},0).to({x:437.6},11).to({x:513.6},6).to({startPosition:0},9).to({startPosition:0},35).to({x:437.6},5).to({x:-200.4},10).to({_off:true},1).wait(28));

	// PATTERN5
	this.instance_1 = new lib.Tween7("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(1030.1,-83.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({_off:false},0).to({y:70.1},11).to({y:91.1},6).to({y:86.1},1).to({startPosition:0},89).to({y:70.1},5).to({y:-83.9},12).to({_off:true},1).wait(30));

	// PATTERN4
	this.instance_2 = new lib.stripepattern();
	this.instance_2.parent = this;
	this.instance_2.setTransform(529.8,804.4,1,1,0,0,0,182.6,82);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(28).to({_off:false},0).to({y:667},11).to({y:633.4},6).to({y:638.4},1).wait(85).to({y:667},6).to({y:804.4},10).to({_off:true},1).wait(10));

	// PATTERN3
	this.instance_3 = new lib.linepattern();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1365.1,-111.2,1,1,0,0,0,185.7,186);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:984.2,y:279.3},11).to({x:893.4,y:368.5},6).to({x:898.4,y:363.5},1).wait(91).to({x:984.2,y:279.3},5).to({x:1365.1,y:-111.2},10).to({_off:true},1).wait(33));

	// PATTERN2
	this.instance_4 = new lib.dotpattern();
	this.instance_4.parent = this;
	this.instance_4.setTransform(582.9,-136,1,1,0,0,0,129.1,129.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(28).to({_off:false},0).to({y:196.7},11).to({y:241},6).to({y:236},1).wait(85).to({y:196.7},6).to({y:-136},10).to({_off:true},1).wait(10));

	// PATTERN1
	this.instance_5 = new lib.pattern();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-135.6,232.2,1,1,0,0,0,132,142.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(22).to({_off:false},0).to({x:199},10).to({x:327.4},7).to({x:322.4},1).wait(85).to({x:199},5).to({x:-135.6},11).to({_off:true},1).wait(16));

	// MASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_11 = new cjs.Graphics().p("APYU7MAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_12 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_13 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_14 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_15 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_16 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_17 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_18 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_19 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_20 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_21 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_22 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_23 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_24 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_25 = new cjs.Graphics().p("APYVEMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_26 = new cjs.Graphics().p("APYWlMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_27 = new cjs.Graphics().p("APYYFMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_28 = new cjs.Graphics().p("APYZmMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_29 = new cjs.Graphics().p("APYaGMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_30 = new cjs.Graphics().p("APYamMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_31 = new cjs.Graphics().p("APYbGMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_32 = new cjs.Graphics().p("APYbmMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_33 = new cjs.Graphics().p("APYcGMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_34 = new cjs.Graphics().p("APYcmMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_35 = new cjs.Graphics().p("APYdGMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_36 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_37 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_38 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_39 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_40 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_41 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_42 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_43 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_44 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_45 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_46 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_47 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_48 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_49 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_50 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_51 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_52 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_53 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_54 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_55 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_56 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_57 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_58 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_59 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_60 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_61 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_62 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_63 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_64 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_65 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_66 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_67 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_68 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_69 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_70 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_71 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_72 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_73 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_74 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_75 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_76 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_77 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_78 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_79 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_80 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_81 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_82 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_83 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_84 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_85 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_86 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_87 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_88 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_89 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_90 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_91 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_92 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_93 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_94 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_95 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_96 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_97 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_98 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_99 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_100 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_101 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_102 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_103 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_104 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_105 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_106 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_107 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_108 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_109 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_110 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_111 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_112 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_113 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_114 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_115 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_116 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_117 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_118 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_119 = new cjs.Graphics().p("A0HU9MAAAgp5MAoPAAAMAAAAp5g");
	var mask_graphics_120 = new cjs.Graphics().p("APYcMMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_121 = new cjs.Graphics().p("APYbrMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_122 = new cjs.Graphics().p("APYbJMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_123 = new cjs.Graphics().p("APYaoMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_124 = new cjs.Graphics().p("APYaHMAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_125 = new cjs.Graphics().p("APYZmMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_126 = new cjs.Graphics().p("APYXCMAAAgp6MAoQAAAMAAAAp6g");
	var mask_graphics_127 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_128 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_129 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_130 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_131 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_132 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_133 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_134 = new cjs.Graphics().p("APYU9MAAAgp5MAoQAAAMAAAAp5g");
	var mask_graphics_135 = new cjs.Graphics().p("APYU7MAAAgp6MAoQAAAMAAAAp6g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(11).to({graphics:mask_graphics_11,x:356,y:-134.4}).wait(1).to({graphics:mask_graphics_12,x:356,y:-115.4}).wait(1).to({graphics:mask_graphics_13,x:356,y:-96.1}).wait(1).to({graphics:mask_graphics_14,x:356,y:-76.8}).wait(1).to({graphics:mask_graphics_15,x:356,y:-57.5}).wait(1).to({graphics:mask_graphics_16,x:356,y:-38.2}).wait(1).to({graphics:mask_graphics_17,x:356,y:-18.9}).wait(1).to({graphics:mask_graphics_18,x:356,y:0.4}).wait(1).to({graphics:mask_graphics_19,x:356,y:19.7}).wait(1).to({graphics:mask_graphics_20,x:356,y:39}).wait(1).to({graphics:mask_graphics_21,x:356,y:58.3}).wait(1).to({graphics:mask_graphics_22,x:356,y:77.6}).wait(1).to({graphics:mask_graphics_23,x:356,y:96.9}).wait(1).to({graphics:mask_graphics_24,x:356,y:116.2}).wait(1).to({graphics:mask_graphics_25,x:356,y:134.8}).wait(1).to({graphics:mask_graphics_26,x:356,y:144.5}).wait(1).to({graphics:mask_graphics_27,x:356,y:154.1}).wait(1).to({graphics:mask_graphics_28,x:356,y:163.8}).wait(1).to({graphics:mask_graphics_29,x:356,y:167}).wait(1).to({graphics:mask_graphics_30,x:356,y:170.2}).wait(1).to({graphics:mask_graphics_31,x:356,y:173.4}).wait(1).to({graphics:mask_graphics_32,x:356,y:176.6}).wait(1).to({graphics:mask_graphics_33,x:356,y:179.8}).wait(1).to({graphics:mask_graphics_34,x:356,y:183}).wait(1).to({graphics:mask_graphics_35,x:356,y:186.2}).wait(1).to({graphics:mask_graphics_36,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_37,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_38,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_39,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_40,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_41,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_42,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_43,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_44,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_45,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_46,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_47,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_48,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_49,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_50,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_51,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_52,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_53,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_54,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_55,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_56,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_57,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_58,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_59,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_60,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_61,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_62,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_63,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_64,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_65,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_66,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_67,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_68,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_69,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_70,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_71,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_72,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_73,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_74,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_75,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_76,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_77,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_78,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_79,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_80,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_81,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_82,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_83,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_84,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_85,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_86,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_87,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_88,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_89,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_90,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_91,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_92,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_93,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_94,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_95,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_96,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_97,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_98,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_99,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_100,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_101,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_102,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_103,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_104,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_105,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_106,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_107,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_108,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_109,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_110,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_111,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_112,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_113,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_114,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_115,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_116,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_117,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_118,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_119,x:583.2,y:233.3}).wait(1).to({graphics:mask_graphics_120,x:356,y:180.4}).wait(1).to({graphics:mask_graphics_121,x:356,y:177.1}).wait(1).to({graphics:mask_graphics_122,x:356,y:173.8}).wait(1).to({graphics:mask_graphics_123,x:356,y:170.4}).wait(1).to({graphics:mask_graphics_124,x:356,y:167.1}).wait(1).to({graphics:mask_graphics_125,x:356,y:163.8}).wait(1).to({graphics:mask_graphics_126,x:356,y:147.4}).wait(1).to({graphics:mask_graphics_127,x:356,y:127.8}).wait(1).to({graphics:mask_graphics_128,x:356,y:95}).wait(1).to({graphics:mask_graphics_129,x:356,y:62.2}).wait(1).to({graphics:mask_graphics_130,x:356,y:29.4}).wait(1).to({graphics:mask_graphics_131,x:356,y:-3.4}).wait(1).to({graphics:mask_graphics_132,x:356,y:-36.2}).wait(1).to({graphics:mask_graphics_133,x:356,y:-69.1}).wait(1).to({graphics:mask_graphics_134,x:356,y:-101.9}).wait(1).to({graphics:mask_graphics_135,x:356,y:-134.4}).wait(23));

	// F
	this.instance_6 = new lib.Tween15("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(526.8,-94.9,0.981,0.981);
	this.instance_6._off = true;
	this.instance_6.filters = [new cjs.ColorFilter(0, 0, 0, 1, 61, 174, 242, 0)];
	this.instance_6.cache(-190,-95,381,190);

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(11).to({_off:false},0).to({regX:0.1,regY:0.1,x:526.9,y:190.4},10).to({y:390.1},7).to({regX:0,regY:0,x:526.8,y:463.7},7).to({regX:0.1,regY:0.1,x:526.9,y:458.7},1).to({regX:0,regY:0,x:526.8},83).to({regX:0.1,regY:0.1,x:526.9,y:390.1},6).to({regX:0,regY:0,x:526.8,y:-94.9},10).to({_off:true},1).wait(22));

	// MASK (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EBWKAcHIdK9KMgAIA6yg");
	var mask_1_graphics_1 = new cjs.Graphics().p("EBTBAcIIdJ9LMgAHA6yg");
	var mask_1_graphics_2 = new cjs.Graphics().p("EBP3AcIIdK9LMgAHA6yg");
	var mask_1_graphics_3 = new cjs.Graphics().p("EBMuAcIIdJ9LMgAGA6yg");
	var mask_1_graphics_4 = new cjs.Graphics().p("EBJkAcIIdK9LMgAHA6yg");
	var mask_1_graphics_5 = new cjs.Graphics().p("EBGbAcIIdJ9LMgAGA6yg");
	var mask_1_graphics_6 = new cjs.Graphics().p("EBDRAcIIdJ9LMgAFA6yg");
	var mask_1_graphics_7 = new cjs.Graphics().p("EBAIAcJIdJ9MMgAFA6yg");
	var mask_1_graphics_8 = new cjs.Graphics().p("EA8/AcJIdI9MMgAFA6yg");
	var mask_1_graphics_9 = new cjs.Graphics().p("EA51AcJIdI9MMgAEA6yg");
	var mask_1_graphics_10 = new cjs.Graphics().p("EA2sAcJIdI9MMgAEA6yg");
	var mask_1_graphics_11 = new cjs.Graphics().p("EAziAcJIdI9MMgADA6yg");
	var mask_1_graphics_12 = new cjs.Graphics().p("EAwZAcKIdI9NMgAEA6yg");
	var mask_1_graphics_13 = new cjs.Graphics().p("EAtQAcKIdH9NMgADA6yg");
	var mask_1_graphics_14 = new cjs.Graphics().p("EAqGAcKIdH9NMgACA6yg");
	var mask_1_graphics_15 = new cjs.Graphics().p("EAm9AcKIdH9NMgADA6yg");
	var mask_1_graphics_16 = new cjs.Graphics().p("EAjzAcKIdH9NMgACA6yg");
	var mask_1_graphics_17 = new cjs.Graphics().p("EAimAcKIdH9OMgACA6zg");
	var mask_1_graphics_18 = new cjs.Graphics().p("EAhZAcJIdH9NMgADA6zg");
	var mask_1_graphics_19 = new cjs.Graphics().p("EAgLAcJIdJ9NMgAFA6zg");
	var mask_1_graphics_20 = new cjs.Graphics().p("Ae+cJIdJ9NMgAFA6zg");
	var mask_1_graphics_21 = new cjs.Graphics().p("AdxcIIdJ9MMgAGA6zg");
	var mask_1_graphics_22 = new cjs.Graphics().p("AckcIIdJ9MMgAGA6zg");
	var mask_1_graphics_23 = new cjs.Graphics().p("AbWcHIdK9LMgAHA6zg");
	var mask_1_graphics_24 = new cjs.Graphics().p("AaJcHIdK9KMgAIA6yg");
	var mask_1_graphics_25 = new cjs.Graphics().p("AakcKIdH9OMgACA6zg");
	var mask_1_graphics_26 = new cjs.Graphics().p("AakcKIdH9OMgACA6zg");
	var mask_1_graphics_27 = new cjs.Graphics().p("AakcKIdH9OMgACA6zg");
	var mask_1_graphics_28 = new cjs.Graphics().p("AakcKIdH9OMgACA6zg");
	var mask_1_graphics_29 = new cjs.Graphics().p("AakcKIdH9OMgACA6zg");
	var mask_1_graphics_30 = new cjs.Graphics().p("AakcKIdH9OMgADA6zg");
	var mask_1_graphics_31 = new cjs.Graphics().p("AakcKIdH9OMgADA6zg");
	var mask_1_graphics_32 = new cjs.Graphics().p("AakcKIdH9OMgADA6zg");
	var mask_1_graphics_33 = new cjs.Graphics().p("AakcKIdH9OMgADA6zg");
	var mask_1_graphics_34 = new cjs.Graphics().p("AakcKIdH9OMgADA6zg");
	var mask_1_graphics_35 = new cjs.Graphics().p("AakcJIdH9NMgADA6zg");
	var mask_1_graphics_36 = new cjs.Graphics().p("AakcJIdH9NMgADA6zg");
	var mask_1_graphics_37 = new cjs.Graphics().p("AakcJIdH9NMgADA6zg");
	var mask_1_graphics_38 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_39 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_40 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_41 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_42 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_43 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_44 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_45 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_46 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_47 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_48 = new cjs.Graphics().p("AajcJIdI9NMgADA6zg");
	var mask_1_graphics_49 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_50 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_51 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_52 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_53 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_54 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_55 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_56 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_57 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_58 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_59 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_60 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_61 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_62 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_63 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_64 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_65 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_66 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_67 = new cjs.Graphics().p("AajcJIdI9NMgAEA6zg");
	var mask_1_graphics_68 = new cjs.Graphics().p("AajcJIdI9NMgAFA6zg");
	var mask_1_graphics_69 = new cjs.Graphics().p("AajcJIdI9NMgAFA6zg");
	var mask_1_graphics_70 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_71 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_72 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_73 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_74 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_75 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_76 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_77 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_78 = new cjs.Graphics().p("AajcIIdI9MMgAFA6zg");
	var mask_1_graphics_79 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_80 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_81 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_82 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_83 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_84 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_85 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_86 = new cjs.Graphics().p("AajcIIdJ9MMgAGA6zg");
	var mask_1_graphics_87 = new cjs.Graphics().p("AaicIIdK9MMgAHA6zg");
	var mask_1_graphics_88 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_89 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_90 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_91 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_92 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_93 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_94 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_95 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_96 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_97 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_98 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_99 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_100 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_101 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_102 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_103 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_104 = new cjs.Graphics().p("AaicIIdK9LMgAHA6yg");
	var mask_1_graphics_105 = new cjs.Graphics().p("AaicHIdK9KMgAHA6yg");
	var mask_1_graphics_106 = new cjs.Graphics().p("AaicHIdK9KMgAIA6yg");
	var mask_1_graphics_107 = new cjs.Graphics().p("AaicHIdK9KMgAIA6yg");
	var mask_1_graphics_108 = new cjs.Graphics().p("AaicHIdK9KMgAIA6yg");
	var mask_1_graphics_109 = new cjs.Graphics().p("AaicHIdK9KMgAIA6yg");
	var mask_1_graphics_110 = new cjs.Graphics().p("Ab3cIIdJ9LMgAHA6yg");
	var mask_1_graphics_111 = new cjs.Graphics().p("AdMcIIdJ9LMgAGA6yg");
	var mask_1_graphics_112 = new cjs.Graphics().p("AegcJIdJ9MMgAFA6yg");
	var mask_1_graphics_113 = new cjs.Graphics().p("Af1cJIdI9MMgAEA6yg");
	var mask_1_graphics_114 = new cjs.Graphics().p("EAhKAcJIdI9MMgAEA6yg");
	var mask_1_graphics_115 = new cjs.Graphics().p("EAifAcKIdH9NMgADA6yg");
	var mask_1_graphics_116 = new cjs.Graphics().p("EAjzAcKIdH9NMgACA6yg");
	var mask_1_graphics_117 = new cjs.Graphics().p("EAnrAcKIdH9OMgACA6zg");
	var mask_1_graphics_118 = new cjs.Graphics().p("EArjAcKIdI9OMgADA6zg");
	var mask_1_graphics_119 = new cjs.Graphics().p("EAvbAcJIdI9NMgAEA6zg");
	var mask_1_graphics_120 = new cjs.Graphics().p("EAzTAcJIdI9NMgAEA6zg");
	var mask_1_graphics_121 = new cjs.Graphics().p("EA3LAcJIdI9NMgAEA6zg");
	var mask_1_graphics_122 = new cjs.Graphics().p("EA7DAcJIdI9NMgAFA6zg");
	var mask_1_graphics_123 = new cjs.Graphics().p("EA+7AcIIdI9MMgAFA6zg");
	var mask_1_graphics_124 = new cjs.Graphics().p("EBCzAcIIdI9MMgAFA6zg");
	var mask_1_graphics_125 = new cjs.Graphics().p("EBGqAcIIdJ9MMgAFA6zg");
	var mask_1_graphics_126 = new cjs.Graphics().p("EBKiAcIIdK9MMgAHA6zg");
	var mask_1_graphics_127 = new cjs.Graphics().p("EBOaAcIIdK9MMgAHA6zg");
	var mask_1_graphics_128 = new cjs.Graphics().p("EBSSAcHIdK9LMgAHA6zg");
	var mask_1_graphics_129 = new cjs.Graphics().p("EBWKAcHIdK9KMgAIA6yg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:738,y:369.5}).wait(1).to({graphics:mask_1_graphics_1,x:717.8,y:369.5}).wait(1).to({graphics:mask_1_graphics_2,x:697.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_3,x:677.5,y:369.5}).wait(1).to({graphics:mask_1_graphics_4,x:657.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_5,x:637.2,y:369.5}).wait(1).to({graphics:mask_1_graphics_6,x:617,y:369.5}).wait(1).to({graphics:mask_1_graphics_7,x:596.9,y:369.5}).wait(1).to({graphics:mask_1_graphics_8,x:576.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_9,x:556.5,y:369.5}).wait(1).to({graphics:mask_1_graphics_10,x:536.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_11,x:516.2,y:369.5}).wait(1).to({graphics:mask_1_graphics_12,x:496.1,y:369.5}).wait(1).to({graphics:mask_1_graphics_13,x:475.9,y:369.5}).wait(1).to({graphics:mask_1_graphics_14,x:455.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_15,x:435.6,y:369.5}).wait(1).to({graphics:mask_1_graphics_16,x:415.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_17,x:407.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_18,x:400,y:369.5}).wait(1).to({graphics:mask_1_graphics_19,x:392.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_20,x:384.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_21,x:377,y:369.5}).wait(1).to({graphics:mask_1_graphics_22,x:369.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_23,x:361.6,y:369.5}).wait(1).to({graphics:mask_1_graphics_24,x:353.9,y:369.5}).wait(1).to({graphics:mask_1_graphics_25,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_26,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_27,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_28,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_29,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_30,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_31,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_32,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_33,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_34,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_35,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_36,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_37,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_38,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_39,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_40,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_41,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_42,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_43,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_44,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_45,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_46,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_47,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_48,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_49,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_50,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_51,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_52,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_53,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_54,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_55,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_56,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_57,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_58,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_59,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_60,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_61,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_62,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_63,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_64,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_65,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_66,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_67,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_68,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_69,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_70,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_71,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_72,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_73,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_74,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_75,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_76,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_77,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_78,x:356.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_79,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_80,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_81,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_82,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_83,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_84,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_85,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_86,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_87,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_88,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_89,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_90,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_91,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_92,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_93,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_94,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_95,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_96,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_97,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_98,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_99,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_100,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_101,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_102,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_103,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_104,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_105,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_106,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_107,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_108,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_109,x:356.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_110,x:364.8,y:369.5}).wait(1).to({graphics:mask_1_graphics_111,x:373.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_112,x:381.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_113,x:390.1,y:369.5}).wait(1).to({graphics:mask_1_graphics_114,x:398.6,y:369.5}).wait(1).to({graphics:mask_1_graphics_115,x:407,y:369.5}).wait(1).to({graphics:mask_1_graphics_116,x:415.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_117,x:440.2,y:369.5}).wait(1).to({graphics:mask_1_graphics_118,x:465.1,y:369.5}).wait(1).to({graphics:mask_1_graphics_119,x:489.9,y:369.5}).wait(1).to({graphics:mask_1_graphics_120,x:514.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_121,x:539.5,y:369.5}).wait(1).to({graphics:mask_1_graphics_122,x:564.3,y:369.5}).wait(1).to({graphics:mask_1_graphics_123,x:589.1,y:369.5}).wait(1).to({graphics:mask_1_graphics_124,x:613.9,y:369.5}).wait(1).to({graphics:mask_1_graphics_125,x:638.7,y:369.5}).wait(1).to({graphics:mask_1_graphics_126,x:663.6,y:369.5}).wait(1).to({graphics:mask_1_graphics_127,x:688.4,y:369.5}).wait(1).to({graphics:mask_1_graphics_128,x:713.2,y:369.5}).wait(1).to({graphics:mask_1_graphics_129,x:738,y:369.5}).wait(29));

	// G
	this.instance_7 = new lib.Tween20("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(529.4,907.2);
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(28).to({_off:false},0).to({y:769.6},11).to({y:736.6},6).to({y:741.6},1).to({startPosition:0},70).to({_off:true},1).wait(41));

	// A
	this.instance_8 = new lib.ClipGroup_19();
	this.instance_8.parent = this;
	this.instance_8.setTransform(718.9,-90.7,5.234,5.234,0,0,0,34.6,17.4);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(35).to({_off:false},0).to({x:718.7,y:-3.8},11).to({x:718.8,y:14.5},6).to({x:718.9,y:9.6},1).to({x:718.8,y:9.5},84).to({x:718.7,y:-3.8},6).to({x:718.9,y:-90.7},10).to({_off:true},1).wait(4));

	// M
	this.instance_9 = new lib.Tween17("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(1030.7,-93.8);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(2).to({_off:false},0).to({y:56.6},11).to({y:91.2},6).to({y:86.2},1).to({startPosition:0},91).to({y:56.6},5).to({y:-93.8},10).to({_off:true},1).wait(31));

	// F
	this.instance_10 = new lib.Tween15("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(1382.6,550.9,1,1,90.1,0,0,0.2,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({regX:0.3,scaleX:1,scaleY:1,rotation:90,x:737.8,y:551.1},16).to({regX:0.2,scaleX:1,scaleY:1,rotation:90.1,x:614.4,y:550.9},8).to({scaleX:1,scaleY:1,rotation:90,x:619.5},1).to({scaleX:1,scaleY:1,rotation:90.1,x:619.4},84).to({regX:0.3,scaleX:1,scaleY:1,rotation:90,x:737.8,y:551.1},7).to({regX:0.2,scaleX:1,scaleY:1,rotation:90.1,x:1382.6,y:550.9},13).to({_off:true},1).wait(28));

	// L
	this.instance_11 = new lib.Tween5("synched",0);
	this.instance_11.parent = this;
	this.instance_11.setTransform(-182.5,9);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(11).to({_off:false},0).to({x:441.6},10).to({x:530.5},14).to({x:525.5},1).to({startPosition:0},83).to({x:441.6},6).to({x:-182.5},10).to({_off:true},1).wait(22));

	// K
	this.instance_12 = new lib.Tween9("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(583.2,-134.7);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(11).to({_off:false},0).to({y:193.4},10).to({y:238.3},14).to({y:233.3},1).to({startPosition:0},83).to({y:193.4},6).to({y:-134.7},10).to({_off:true},1).wait(22));

	// G
	this.instance_13 = new lib.Group_1_4();
	this.instance_13.parent = this;
	this.instance_13.setTransform(1401,729.1,5.294,5.294,0,0,0,20.4,19.8);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(5).to({_off:false},0).to({scaleX:5.29,scaleY:5.29,x:1102,y:729.2},11).to({scaleX:5.29,scaleY:5.29,x:1063.8},14).to({scaleX:5.29,scaleY:5.29,x:1068.8,y:729.1},1).to({scaleX:5.29,scaleY:5.29,y:729.2},81).to({scaleX:5.29,scaleY:5.29,x:1102},6).to({scaleX:5.29,scaleY:5.29,x:1401,y:729.1},10).to({_off:true},1).wait(29));

	// D
	this.instance_14 = new lib.Group_3_0();
	this.instance_14.parent = this;
	this.instance_14.setTransform(1379.5,909.5,5.299,5.299,0,0,0,17.4,34.8);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(3).to({_off:false},0).to({x:902.6,y:649.9},11).to({x:804.6,y:551.5},6).to({x:799.7,y:546.6},1).to({x:804.6,y:551.5},88).to({x:902.6,y:649.9},5).to({x:1379.5,y:909.5},10).to({_off:true},1).wait(33));

	// B
	this.instance_15 = new lib.Tween13("synched",0);
	this.instance_15.parent = this;
	this.instance_15.setTransform(95.2,-98.2);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(35).to({_off:false},0).to({y:158.1},11).to({y:200.8},6).to({y:195.8},1).to({startPosition:0},84).to({y:158.1},6).to({y:-98.2},10).to({_off:true},1).wait(4));

	// E
	this.instance_16 = new lib.Group_2_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(-92.2,553.1,5.357,5.357,0,0,0,17.8,34.8);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(11).to({_off:false},0).to({scaleX:5.36,scaleY:5.36,x:223.6},17).to({x:258.9},7).to({x:253.8},1).to({x:253.9},83).to({x:223.6},6).to({scaleX:5.36,scaleY:5.36,x:-92.2},10).to({_off:true},1).wait(22));

	// F
	this.instance_17 = new lib.Tween15("synched",0);
	this.instance_17.parent = this;
	this.instance_17.setTransform(526.8,-94.9,0.981,0.981);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(11).to({_off:false},0).to({regX:0.1,regY:0.1,x:526.9,y:390.1},17).to({regX:0,regY:0,x:526.8,y:463.7},7).to({regX:0.1,regY:0.1,x:526.9,y:458.7},1).to({regX:0,regY:0,x:526.8},83).to({regX:0.1,regY:0.1,x:526.9,y:390.1},6).to({regX:0,regY:0,x:526.8,y:-94.9},10).to({_off:true},1).wait(22));

	// F
	this.instance_18 = new lib.Tween15("synched",0);
	this.instance_18.parent = this;
	this.instance_18.setTransform(1472.1,269.9);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(22).to({_off:false},0).to({x:1120.4},17).to({x:1081.1},7).to({x:1086.1},1).to({startPosition:0},78).to({x:1120.4},6).to({x:1472.1},10).to({_off:true},1).wait(16));

	// H
	this.instance_19 = new lib.Group_3_0();
	this.instance_19.parent = this;
	this.instance_19.setTransform(1380.9,371.6,5.585,5.585,180,0,0,17.4,34.6);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(11).to({_off:false},0).to({scaleX:5.58,scaleY:5.58,x:1216.6,y:371.9},11).to({x:1177.8,y:371.8},6).to({x:1182.7,y:371.9},1).to({x:1182.8,y:371.8},90).to({x:1216.6,y:371.9},6).to({scaleX:5.59,scaleY:5.59,x:1380.9,y:371.6},10).to({_off:true},1).wait(22));

	// N
	this.instance_20 = new lib.Tween18("synched",0);
	this.instance_20.parent = this;
	this.instance_20.setTransform(522.1,822.4);
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(22).to({_off:false},0).to({y:696},11).to({y:641.4},6).to({y:646.4},1).to({startPosition:0},85).to({y:696},6).to({y:822.4},10).to({_off:true},1).wait(16));

	// J
	this.instance_21 = new lib.ClipGroup_52();
	this.instance_21.parent = this;
	this.instance_21.setTransform(293.5,-101.8,5.234,5.234,0,0,0,19.7,19.6);
	this.instance_21._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(39).to({_off:false},0).to({x:293.3,y:-58.6},11).to({x:293.4,y:-48.6},6).to({x:293.3,y:-53.6},1).to({x:293.4},85).to({x:293.3,y:-58.6},5).to({x:293.5,y:-101.8},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1819.4,62.8,371.3,1036.3);
// library properties:
lib.properties = {
	width: 1280,
	height: 720,
	fps: 24,
	color: "#F2F2F2",
	opacity: 1.00,
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;